# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GreenSignaliOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GreenSignaliOS
# Pods for NetworkStatusMonitor
inhibit_all_warnings!
pod ‘ReachabilitySwift’, ‘~> 3’ # Adds the library to your project
pod 'Firebase/Messaging'
pod 'Firebase/Analytics'
pod 'Fabric'
pod 'Crashlytics'
pod 'Alamofire', '~> 4.4'
pod 'SwiftyJSON', '~> 4.0'
pod 'SDWebImage', '~> 5.0'
pod 'Loaf'
pod 'MKProgress', :git => 'https://github.com/kamirana4/MKProgress.git'
pod 'HCSStarRatingView', '~> 1.5'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
end

target 'GreenSignalmacOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GreenSignalmacOS
pod ‘ReachabilitySwift’, ‘~> 3’ # Adds the library to your project
pod 'Alamofire', '~> 4.4'
pod 'SwiftyJSON', '~> 4.0'
pod 'SDWebImage', '~> 5.0'
end

target 'GreenSignalmacOSLoginItemHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GreenSignalmacOSLoginItemHelper

end

target 'GreenSignalNetworkExtensioniOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GreenSignalNetworkExtensioniOS

end

target 'GreenSignalNetworkExtensionmacOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GreenSignalNetworkExtensionmacOS

end
